<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>server_goose_publisher</AssemblyTitle>
    <Product>server_goose_publisher</Product>
    <Copyright>Copyright ©  2021</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
	<Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <None Update="simpleIO_direct_control_goose.cfg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IEC61850forCSharp\IEC61850.NET.csproj" />
  </ItemGroup>
</Project>