<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>authenticate</AssemblyTitle>
    <Copyright>mzillgit</Copyright>
	<Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.%2a</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <Externalconsole>true</Externalconsole>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <Externalconsole>true</Externalconsole>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IEC61850forCSharp\IEC61850.NET.csproj" />
  </ItemGroup>
</Project>