<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>log_client</AssemblyTitle>
    <Copyright>mzillgit</Copyright>
    <AssemblyVersion>1.0.%2a</AssemblyVersion>
	<Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IEC61850forCSharp\IEC61850.NET.csproj" />
  </ItemGroup>
</Project>