/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_AccessResult_H_
#define	_AccessResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataAccessError.h"
#include "DataSequence.h"
#include <BOOLEAN.h>
#include <BIT_STRING.h>
#include <INTEGER.h>
#include "FloatingPoint.h"
#include <OCTET_STRING.h>
#include <VisibleString.h>
#include <GeneralizedTime.h>
#include "TimeOfDay.h"
#include "MMSString.h"
#include "UtcTime.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccessResult_PR {
	AccessResult_PR_NOTHING,	/* No components present */
	AccessResult_PR_failure,
	AccessResult_PR_array,
	AccessResult_PR_structure,
	AccessResult_PR_boolean,
	AccessResult_PR_bitstring,
	AccessResult_PR_integer,
	AccessResult_PR_unsigned,
	AccessResult_PR_floatingpoint,
	AccessResult_PR_octetstring,
	AccessResult_PR_visiblestring,
	AccessResult_PR_generalizedtime,
	AccessResult_PR_binarytime,
	AccessResult_PR_bcd,
	AccessResult_PR_booleanArray,
	AccessResult_PR_mMSString,
	AccessResult_PR_utctime
} AccessResult_PR;

/* AccessResult */
typedef struct AccessResult {
	AccessResult_PR present;
	union AccessResult_u {
		DataAccessError_t	 failure;
		DataSequence_t	 array;
		DataSequence_t	 structure;
		BOOLEAN_t	 boolean;
		BIT_STRING_t	 bitstring;
		INTEGER_t	 integer;
		INTEGER_t	 Unsigned;
		FloatingPoint_t	 floatingpoint;
		OCTET_STRING_t	 octetstring;
		VisibleString_t	 visiblestring;
		GeneralizedTime_t	 generalizedtime;
		TimeOfDay_t	 binarytime;
		INTEGER_t	 bcd;
		BIT_STRING_t	 booleanArray;
		MMSString_t	 mMSString;
		UtcTime_t	 utctime;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccessResult_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_AccessResult;

#ifdef __cplusplus
}
#endif

#endif	/* _AccessResult_H_ */
