/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "AlternateAccessSelection.h"

static asn_TYPE_member_t asn_MBR_indexRange_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection__indexRange, lowIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lowIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection__indexRange, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfElements"
		},
};
static ber_tlv_tag_t asn_DEF_indexRange_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_indexRange_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lowIndex at 551 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* numberOfElements at 553 */
};
static asn_SEQUENCE_specifics_t asn_SPC_indexRange_specs_6 = {
	sizeof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection__indexRange),
	offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection__indexRange, _asn_ctx),
	asn_MAP_indexRange_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_indexRange_6 = {
	"indexRange",
	"indexRange",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_indexRange_tags_6,
	sizeof(asn_DEF_indexRange_tags_6)
		/sizeof(asn_DEF_indexRange_tags_6[0]) - 1, /* 1 */
	asn_DEF_indexRange_tags_6,	/* Same as above */
	sizeof(asn_DEF_indexRange_tags_6)
		/sizeof(asn_DEF_indexRange_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_indexRange_6,
	2,	/* Elements count */
	&asn_SPC_indexRange_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_accessSelection_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection, choice.component),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection, choice.indexRange),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_indexRange_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection, choice.allElements),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allElements"
		},
};
static asn_TYPE_tag2member_t asn_MAP_accessSelection_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* component at 548 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* index at 549 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* indexRange at 551 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* allElements at 554 */
};
static asn_CHOICE_specifics_t asn_SPC_accessSelection_specs_3 = {
	sizeof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection),
	offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection, _asn_ctx),
	offsetof(struct AlternateAccessSelection__selectAlternateAccess__accessSelection, present),
	sizeof(((struct AlternateAccessSelection__selectAlternateAccess__accessSelection *)0)->present),
	asn_MAP_accessSelection_tag2el_3,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_accessSelection_3 = {
	"accessSelection",
	"accessSelection",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_accessSelection_3,
	4,	/* Elements count */
	&asn_SPC_accessSelection_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_selectAlternateAccess_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess, accessSelection),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_accessSelection_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessSelection"
		},
	{ ATF_POINTER, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess, alternateAccess),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlternateAccess,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternateAccess"
		},
};
static ber_tlv_tag_t asn_DEF_selectAlternateAccess_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_selectAlternateAccess_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* alternateAccess at 558 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* component at 548 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* index at 549 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* indexRange at 551 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* allElements at 554 */
};
static asn_SEQUENCE_specifics_t asn_SPC_selectAlternateAccess_specs_2 = {
	sizeof(struct AlternateAccessSelection__selectAlternateAccess),
	offsetof(struct AlternateAccessSelection__selectAlternateAccess, _asn_ctx),
	asn_MAP_selectAlternateAccess_tag2el_2,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_selectAlternateAccess_2 = {
	"selectAlternateAccess",
	"selectAlternateAccess",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_selectAlternateAccess_tags_2,
	sizeof(asn_DEF_selectAlternateAccess_tags_2)
		/sizeof(asn_DEF_selectAlternateAccess_tags_2[0]) - 1, /* 1 */
	asn_DEF_selectAlternateAccess_tags_2,	/* Same as above */
	sizeof(asn_DEF_selectAlternateAccess_tags_2)
		/sizeof(asn_DEF_selectAlternateAccess_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_selectAlternateAccess_2,
	2,	/* Elements count */
	&asn_SPC_selectAlternateAccess_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_indexRange_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAccess__indexRange, lowIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lowIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAccess__indexRange, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfElements"
		},
};
static ber_tlv_tag_t asn_DEF_indexRange_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_indexRange_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lowIndex at 564 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* numberOfElements at 566 */
};
static asn_SEQUENCE_specifics_t asn_SPC_indexRange_specs_14 = {
	sizeof(struct AlternateAccessSelection__selectAccess__indexRange),
	offsetof(struct AlternateAccessSelection__selectAccess__indexRange, _asn_ctx),
	asn_MAP_indexRange_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_indexRange_14 = {
	"indexRange",
	"indexRange",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_indexRange_tags_14,
	sizeof(asn_DEF_indexRange_tags_14)
		/sizeof(asn_DEF_indexRange_tags_14[0]) - 1, /* 1 */
	asn_DEF_indexRange_tags_14,	/* Same as above */
	sizeof(asn_DEF_indexRange_tags_14)
		/sizeof(asn_DEF_indexRange_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_indexRange_14,
	2,	/* Elements count */
	&asn_SPC_indexRange_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_selectAccess_11[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAccess, choice.component),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAccess, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAccess, choice.indexRange),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_indexRange_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAccess, choice.allElements),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allElements"
		},
};
static asn_TYPE_tag2member_t asn_MAP_selectAccess_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* component at 561 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* index at 562 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* indexRange at 564 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 } /* allElements at 567 */
};
static asn_CHOICE_specifics_t asn_SPC_selectAccess_specs_11 = {
	sizeof(struct AlternateAccessSelection__selectAccess),
	offsetof(struct AlternateAccessSelection__selectAccess, _asn_ctx),
	offsetof(struct AlternateAccessSelection__selectAccess, present),
	sizeof(((struct AlternateAccessSelection__selectAccess *)0)->present),
	asn_MAP_selectAccess_tag2el_11,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_selectAccess_11 = {
	"selectAccess",
	"selectAccess",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_selectAccess_11,
	4,	/* Elements count */
	&asn_SPC_selectAccess_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_AlternateAccessSelection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection, choice.selectAlternateAccess),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_selectAlternateAccess_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"selectAlternateAccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection, choice.selectAccess),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_selectAccess_11,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"selectAccess"
		},
};
static asn_TYPE_tag2member_t asn_MAP_AlternateAccessSelection_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* selectAlternateAccess at 555 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* component at 561 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* index at 562 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* indexRange at 564 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 } /* allElements at 567 */
};
static asn_CHOICE_specifics_t asn_SPC_AlternateAccessSelection_specs_1 = {
	sizeof(struct AlternateAccessSelection),
	offsetof(struct AlternateAccessSelection, _asn_ctx),
	offsetof(struct AlternateAccessSelection, present),
	sizeof(((struct AlternateAccessSelection *)0)->present),
	asn_MAP_AlternateAccessSelection_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AlternateAccessSelection = {
	"AlternateAccessSelection",
	"AlternateAccessSelection",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_AlternateAccessSelection_1,
	2,	/* Elements count */
	&asn_SPC_AlternateAccessSelection_specs_1	/* Additional specs */
};

