/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_ConcludeRequestPDU_H_
#define	_ConcludeRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConcludeRequestPDU */
typedef NULL_t	 ConcludeRequestPDU_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_ConcludeRequestPDU;
LIB61850_INTERNAL asn_struct_free_f ConcludeRequestPDU_free;
LIB61850_INTERNAL asn_struct_print_f ConcludeRequestPDU_print;
LIB61850_INTERNAL asn_constr_check_f ConcludeRequestPDU_constraint;
LIB61850_INTERNAL ber_type_decoder_f ConcludeRequestPDU_decode_ber;
LIB61850_INTERNAL der_type_encoder_f ConcludeRequestPDU_encode_der;
LIB61850_INTERNAL xer_type_decoder_f ConcludeRequestPDU_decode_xer;
LIB61850_INTERNAL xer_type_encoder_f ConcludeRequestPDU_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConcludeRequestPDU_H_ */
