/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "ConfirmedServiceRequest.h"

static asn_TYPE_member_t asn_MBR_ConfirmedServiceRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceRequest, choice.getNameList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetNameListRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"getNameList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceRequest, choice.read),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReadRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"read"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceRequest, choice.write),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WriteRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"write"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceRequest, choice.getVariableAccessAttributes),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetVariableAccessAttributesRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"getVariableAccessAttributes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceRequest, choice.defineNamedVariableList),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DefineNamedVariableListRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defineNamedVariableList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceRequest, choice.getNamedVariableListAttributes),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetNamedVariableListAttributesRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"getNamedVariableListAttributes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceRequest, choice.deleteNamedVariableList),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeleteNamedVariableListRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"deleteNamedVariableList"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ConfirmedServiceRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* getNameList at 127 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* read at 128 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* write at 129 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, 0, 0 }, /* getVariableAccessAttributes at 130 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 4, 0, 0 }, /* defineNamedVariableList at 131 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 5, 0, 0 }, /* getNamedVariableListAttributes at 132 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 6, 0, 0 } /* deleteNamedVariableList at 136 */
};
static asn_CHOICE_specifics_t asn_SPC_ConfirmedServiceRequest_specs_1 = {
	sizeof(struct ConfirmedServiceRequest),
	offsetof(struct ConfirmedServiceRequest, _asn_ctx),
	offsetof(struct ConfirmedServiceRequest, present),
	sizeof(((struct ConfirmedServiceRequest *)0)->present),
	asn_MAP_ConfirmedServiceRequest_tag2el_1,
	7,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ConfirmedServiceRequest = {
	"ConfirmedServiceRequest",
	"ConfirmedServiceRequest",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ConfirmedServiceRequest_1,
	7,	/* Elements count */
	&asn_SPC_ConfirmedServiceRequest_specs_1	/* Additional specs */
};

