/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_ConfirmedErrorPDU_H_
#define	_ConfirmedErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include "ServiceError.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfirmedErrorPDU */
typedef struct ConfirmedErrorPDU {
	Unsigned32_t	 invokeID;
	ServiceError_t	 serviceError;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfirmedErrorPDU_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_ConfirmedErrorPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfirmedErrorPDU_H_ */
