/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "ConfirmedServiceResponse.h"

static asn_TYPE_member_t asn_MBR_ConfirmedServiceResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.getNameList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetNameListResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"getNameList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.read),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReadResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"read"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.write),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WriteResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"write"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.getVariableAccessAttributes),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetVariableAccessAttributesResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"getVariableAccessAttributes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.defineNamedVariableList),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DefineNamedVariableListResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defineNamedVariableList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.getNamedVariableListAttributes),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetNamedVariableListAttributesResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"getNamedVariableListAttributes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.deleteNamedVariableList),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeleteNamedVariableListResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"deleteNamedVariableList"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ConfirmedServiceResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* getNameList at 140 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* read at 141 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* write at 142 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, 0, 0 }, /* getVariableAccessAttributes at 143 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 4, 0, 0 }, /* defineNamedVariableList at 144 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 5, 0, 0 }, /* getNamedVariableListAttributes at 145 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 6, 0, 0 } /* deleteNamedVariableList at 147 */
};
static asn_CHOICE_specifics_t asn_SPC_ConfirmedServiceResponse_specs_1 = {
	sizeof(struct ConfirmedServiceResponse),
	offsetof(struct ConfirmedServiceResponse, _asn_ctx),
	offsetof(struct ConfirmedServiceResponse, present),
	sizeof(((struct ConfirmedServiceResponse *)0)->present),
	asn_MAP_ConfirmedServiceResponse_tag2el_1,
	7,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ConfirmedServiceResponse = {
	"ConfirmedServiceResponse",
	"ConfirmedServiceResponse",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ConfirmedServiceResponse_1,
	7,	/* Elements count */
	&asn_SPC_ConfirmedServiceResponse_specs_1	/* Additional specs */
};

