/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Data_H_
#define	_Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <BIT_STRING.h>
#include <INTEGER.h>
#include "FloatingPoint.h"
#include <OCTET_STRING.h>
#include <VisibleString.h>
#include <GeneralizedTime.h>
#include "TimeOfDay.h"
#include "MMSString.h"
#include "UtcTime.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Data_PR {
	Data_PR_NOTHING,	/* No components present */
	Data_PR_array,
	Data_PR_structure,
	Data_PR_boolean,
	Data_PR_bitstring,
	Data_PR_integer,
	Data_PR_unsigned,
	Data_PR_floatingpoint,
	Data_PR_octetstring,
	Data_PR_visiblestring,
	Data_PR_generalizedtime,
	Data_PR_binarytime,
	Data_PR_bcd,
	Data_PR_booleanArray,
	Data_PR_mMSString,
	Data_PR_utctime
} Data_PR;

/* Forward declarations */
struct DataSequence;

/* Data */
typedef struct Data {
	Data_PR present;
	union Data_u {
		struct DataSequence	*array;
		struct DataSequence	*structure;
		BOOLEAN_t	 boolean;
		BIT_STRING_t	 bitstring;
		INTEGER_t	 integer;
		INTEGER_t	 Unsigned;
		FloatingPoint_t	 floatingpoint;
		OCTET_STRING_t	 octetstring;
		VisibleString_t	 visiblestring;
		GeneralizedTime_t	 generalizedtime;
		TimeOfDay_t	 binarytime;
		INTEGER_t	 bcd;
		BIT_STRING_t	 booleanArray;
		MMSString_t	 mMSString;
		UtcTime_t	 utctime;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Data_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_Data;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DataSequence.h"

#endif	/* _Data_H_ */
