/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_GetNamedVariableListAttributesResponse_H_
#define	_GetNamedVariableListAttributesResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "VariableSpecification.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternateAccess;

struct GetNamedVariableListAttributesResponse__listOfVariable__Member {
			VariableSpecification_t	 variableSpecification;
			struct AlternateAccess	*alternateAccess	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ;

struct GetNamedVariableListAttributesResponse__listOfVariable {
		A_SEQUENCE_OF(struct GetNamedVariableListAttributesResponse__listOfVariable__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	};

/* GetNamedVariableListAttributesResponse */
typedef struct GetNamedVariableListAttributesResponse {
	BOOLEAN_t	 mmsDeletable;
	struct GetNamedVariableListAttributesResponse__listOfVariable listOfVariable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetNamedVariableListAttributesResponse_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_GetNamedVariableListAttributesResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternateAccess.h"

#endif	/* _GetNamedVariableListAttributesResponse_H_ */
