/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "GetVariableAccessAttributesRequest.h"

static asn_TYPE_member_t asn_MBR_GetVariableAccessAttributesRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetVariableAccessAttributesRequest, choice.name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetVariableAccessAttributesRequest, choice.address),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Address,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"address"
		},
};
static asn_TYPE_tag2member_t asn_MAP_GetVariableAccessAttributesRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* name at 607 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* address at 609 */
};
static asn_CHOICE_specifics_t asn_SPC_GetVariableAccessAttributesRequest_specs_1 = {
	sizeof(struct GetVariableAccessAttributesRequest),
	offsetof(struct GetVariableAccessAttributesRequest, _asn_ctx),
	offsetof(struct GetVariableAccessAttributesRequest, present),
	sizeof(((struct GetVariableAccessAttributesRequest *)0)->present),
	asn_MAP_GetVariableAccessAttributesRequest_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_GetVariableAccessAttributesRequest = {
	"GetVariableAccessAttributesRequest",
	"GetVariableAccessAttributesRequest",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_GetVariableAccessAttributesRequest_1,
	2,	/* Elements count */
	&asn_SPC_GetVariableAccessAttributesRequest_specs_1	/* Additional specs */
};

