/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_InitRequestDetail_H_
#define	_InitRequestDetail_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Integer16.h"
#include "ParameterSupportOptions.h"
#include "ServiceSupportOptions.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitRequestDetail */
typedef struct InitRequestDetail {
	Integer16_t	 proposedVersionNumber;
	ParameterSupportOptions_t	 proposedParameterCBB;
	ServiceSupportOptions_t	 servicesSupportedCalling;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitRequestDetail_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_InitRequestDetail;

#ifdef __cplusplus
}
#endif

#endif	/* _InitRequestDetail_H_ */
