/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "InitiateResponsePdu.h"

static asn_TYPE_member_t asn_MBR_InitiateResponsePdu_1[] = {
	{ ATF_POINTER, 1, offsetof(struct InitiateResponsePdu, localDetailCalled),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"localDetailCalled"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateResponsePdu, negotiatedMaxServOutstandingCalling),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer16,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"negotiatedMaxServOutstandingCalling"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateResponsePdu, negotiatedMaxServOutstandingCalled),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer16,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"negotiatedMaxServOutstandingCalled"
		},
	{ ATF_POINTER, 1, offsetof(struct InitiateResponsePdu, negotiatedDataStructureNestingLevel),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"negotiatedDataStructureNestingLevel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateResponsePdu, mmsInitResponseDetail),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitResponseDetail,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mmsInitResponseDetail"
		},
};
static ber_tlv_tag_t asn_DEF_InitiateResponsePdu_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_InitiateResponsePdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* localDetailCalled at 201 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* negotiatedMaxServOutstandingCalling at 202 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* negotiatedMaxServOutstandingCalled at 203 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* negotiatedDataStructureNestingLevel at 204 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* mmsInitResponseDetail at 206 */
};
static asn_SEQUENCE_specifics_t asn_SPC_InitiateResponsePdu_specs_1 = {
	sizeof(struct InitiateResponsePdu),
	offsetof(struct InitiateResponsePdu, _asn_ctx),
	asn_MAP_InitiateResponsePdu_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_InitiateResponsePdu = {
	"InitiateResponsePdu",
	"InitiateResponsePdu",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_InitiateResponsePdu_tags_1,
	sizeof(asn_DEF_InitiateResponsePdu_tags_1)
		/sizeof(asn_DEF_InitiateResponsePdu_tags_1[0]), /* 1 */
	asn_DEF_InitiateResponsePdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitiateResponsePdu_tags_1)
		/sizeof(asn_DEF_InitiateResponsePdu_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_InitiateResponsePdu_1,
	5,	/* Elements count */
	&asn_SPC_InitiateResponsePdu_specs_1	/* Additional specs */
};

