/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Integer8_H_
#define	_Integer8_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Integer8 */
typedef long	 Integer8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Integer8;
asn_struct_free_f Integer8_free;
asn_struct_print_f Integer8_print;
asn_constr_check_f Integer8_constraint;
ber_type_decoder_f Integer8_decode_ber;
der_type_encoder_f Integer8_encode_der;
xer_type_decoder_f Integer8_decode_xer;
xer_type_encoder_f Integer8_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Integer8_H_ */
