/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "ListOfVariableSeq.h"

static asn_TYPE_member_t asn_MBR_ListOfVariableSeq_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ListOfVariableSeq, variableSpecification),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_VariableSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"variableSpecification"
		},
	{ ATF_POINTER, 1, offsetof(struct ListOfVariableSeq, alternateAccess),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlternateAccess,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternateAccess"
		},
};
static ber_tlv_tag_t asn_DEF_ListOfVariableSeq_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ListOfVariableSeq_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* name at 772 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* address at 773 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* variableDescription at 776 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* scatteredAccessDescription at 779 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 }, /* invalidated at 780 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 } /* alternateAccess at 767 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ListOfVariableSeq_specs_1 = {
	sizeof(struct ListOfVariableSeq),
	offsetof(struct ListOfVariableSeq, _asn_ctx),
	asn_MAP_ListOfVariableSeq_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ListOfVariableSeq = {
	"ListOfVariableSeq",
	"ListOfVariableSeq",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ListOfVariableSeq_tags_1,
	sizeof(asn_DEF_ListOfVariableSeq_tags_1)
		/sizeof(asn_DEF_ListOfVariableSeq_tags_1[0]), /* 1 */
	asn_DEF_ListOfVariableSeq_tags_1,	/* Same as above */
	sizeof(asn_DEF_ListOfVariableSeq_tags_1)
		/sizeof(asn_DEF_ListOfVariableSeq_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ListOfVariableSeq_1,
	2,	/* Elements count */
	&asn_SPC_ListOfVariableSeq_specs_1	/* Additional specs */
};

