/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "ObjectName.h"

static asn_TYPE_member_t asn_MBR_domainspecific_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectName__domainspecific, domainId),
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domainId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectName__domainspecific, itemId),
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"itemId"
		},
};
static ber_tlv_tag_t asn_DEF_domainspecific_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_domainspecific_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (26 << 2)), 0, 0, 1 }, /* domainId at 172 */
    { (ASN_TAG_CLASS_UNIVERSAL | (26 << 2)), 1, -1, 0 } /* itemId at 174 */
};
static asn_SEQUENCE_specifics_t asn_SPC_domainspecific_specs_3 = {
	sizeof(struct ObjectName__domainspecific),
	offsetof(struct ObjectName__domainspecific, _asn_ctx),
	asn_MAP_domainspecific_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_domainspecific_3 = {
	"domainspecific",
	"domainspecific",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_domainspecific_tags_3,
	sizeof(asn_DEF_domainspecific_tags_3)
		/sizeof(asn_DEF_domainspecific_tags_3[0]) - 1, /* 1 */
	asn_DEF_domainspecific_tags_3,	/* Same as above */
	sizeof(asn_DEF_domainspecific_tags_3)
		/sizeof(asn_DEF_domainspecific_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_domainspecific_3,
	2,	/* Elements count */
	&asn_SPC_domainspecific_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ObjectName_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectName, choice.vmdspecific),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vmdspecific"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectName, choice.domainspecific),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_domainspecific_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domainspecific"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectName, choice.aaspecific),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aaspecific"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ObjectName_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vmdspecific at 169 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* domainspecific at 172 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* aaspecific at 176 */
};
static asn_CHOICE_specifics_t asn_SPC_ObjectName_specs_1 = {
	sizeof(struct ObjectName),
	offsetof(struct ObjectName, _asn_ctx),
	offsetof(struct ObjectName, present),
	sizeof(((struct ObjectName *)0)->present),
	asn_MAP_ObjectName_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ObjectName = {
	"ObjectName",
	"ObjectName",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ObjectName_1,
	3,	/* Elements count */
	&asn_SPC_ObjectName_specs_1	/* Additional specs */
};

