/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_ReadResponse_H_
#define	_ReadResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariableAccessSpecification;
struct AccessResult;

struct ReadResponse__listOfAccessResult {
		A_SEQUENCE_OF(struct AccessResult) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	};

/* ReadResponse */
typedef struct ReadResponse {
	struct VariableAccessSpecification	*variableAccessSpecification	/* OPTIONAL */;
	struct ReadResponse__listOfAccessResult listOfAccessResult;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReadResponse_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_ReadResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableAccessSpecification.h"
#include "AccessResult.h"

#endif	/* _ReadResponse_H_ */
