/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "ServiceError.h"

static asn_TYPE_member_t asn_MBR_errorClass_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.vmdstate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vmdstate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.applicationreference),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"applicationreference"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.definition),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"definition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.resource),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resource"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.service),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"service"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.servicepreempt),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servicepreempt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.timeresolution),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeresolution"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.access),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"access"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.initiate),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"initiate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.conclude),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"conclude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.cancel),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cancel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.file),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"file"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.others),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"others"
		},
};
static asn_TYPE_tag2member_t asn_MAP_errorClass_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vmdstate at 328 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* applicationreference at 336 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* definition at 344 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* resource at 354 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* service at 363 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* servicepreempt at 372 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* timeresolution at 379 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* access at 384 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* initiate at 392 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* conclude at 403 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* cancel at 408 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* file at 414 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 } /* others at 426 */
};
static asn_CHOICE_specifics_t asn_SPC_errorClass_specs_2 = {
	sizeof(struct ServiceError__errorClass),
	offsetof(struct ServiceError__errorClass, _asn_ctx),
	offsetof(struct ServiceError__errorClass, present),
	sizeof(((struct ServiceError__errorClass *)0)->present),
	asn_MAP_errorClass_tag2el_2,
	13,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_errorClass_2 = {
	"errorClass",
	"errorClass",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_errorClass_2,
	13,	/* Elements count */
	&asn_SPC_errorClass_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ServiceError_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError, errorClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_errorClass_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"errorClass"
		},
	{ ATF_POINTER, 2, offsetof(struct ServiceError, additionalCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additionalCode"
		},
	{ ATF_POINTER, 1, offsetof(struct ServiceError, additionalDescription),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additionalDescription"
		},
};
static ber_tlv_tag_t asn_DEF_ServiceError_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ServiceError_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* errorClass at 333 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* additionalCode at 427 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* additionalDescription at 428 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ServiceError_specs_1 = {
	sizeof(struct ServiceError),
	offsetof(struct ServiceError, _asn_ctx),
	asn_MAP_ServiceError_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServiceError = {
	"ServiceError",
	"ServiceError",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ServiceError_tags_1,
	sizeof(asn_DEF_ServiceError_tags_1)
		/sizeof(asn_DEF_ServiceError_tags_1[0]), /* 1 */
	asn_DEF_ServiceError_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceError_tags_1)
		/sizeof(asn_DEF_ServiceError_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ServiceError_1,
	3,	/* Elements count */
	&asn_SPC_ServiceError_specs_1	/* Additional specs */
};

