/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_StructComponent_H_
#define	_StructComponent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TypeSpecification;

/* StructComponent */
typedef struct StructComponent {
	Identifier_t	*componentName	/* OPTIONAL */;
	struct TypeSpecification	*componentType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StructComponent_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_StructComponent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TypeSpecification.h"

#endif	/* _StructComponent_H_ */
