/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "StructComponent.h"

static asn_TYPE_member_t asn_MBR_StructComponent_1[] = {
	{ ATF_POINTER, 1, offsetof(struct StructComponent, componentName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"componentName"
		},
	{ ATF_POINTER, 0, offsetof(struct StructComponent, componentType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"componentType"
		},
};
static ber_tlv_tag_t asn_DEF_StructComponent_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_StructComponent_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* componentName at 533 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* componentType at 535 */
};
static asn_SEQUENCE_specifics_t asn_SPC_StructComponent_specs_1 = {
	sizeof(struct StructComponent),
	offsetof(struct StructComponent, _asn_ctx),
	asn_MAP_StructComponent_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_StructComponent = {
	"StructComponent",
	"StructComponent",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_StructComponent_tags_1,
	sizeof(asn_DEF_StructComponent_tags_1)
		/sizeof(asn_DEF_StructComponent_tags_1[0]), /* 1 */
	asn_DEF_StructComponent_tags_1,	/* Same as above */
	sizeof(asn_DEF_StructComponent_tags_1)
		/sizeof(asn_DEF_StructComponent_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_StructComponent_1,
	2,	/* Elements count */
	&asn_SPC_StructComponent_specs_1	/* Additional specs */
};

