/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_UnconfirmedService_H_
#define	_UnconfirmedService_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InformationReport.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnconfirmedService_PR {
	UnconfirmedService_PR_NOTHING,	/* No components present */
	UnconfirmedService_PR_informationReport
} UnconfirmedService_PR;

/* UnconfirmedService */
typedef struct UnconfirmedService {
	UnconfirmedService_PR present;
	union UnconfirmedService_u {
		InformationReport_t	 informationReport;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnconfirmedService_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_UnconfirmedService;

#ifdef __cplusplus
}
#endif

#endif	/* _UnconfirmedService_H_ */
