/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Unsigned32_H_
#define	_Unsigned32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Unsigned32 */
typedef INTEGER_t	 Unsigned32_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_Unsigned32;
LIB61850_INTERNAL asn_struct_free_f Unsigned32_free;
LIB61850_INTERNAL asn_struct_print_f Unsigned32_print;
LIB61850_INTERNAL asn_constr_check_f Unsigned32_constraint;
LIB61850_INTERNAL ber_type_decoder_f Unsigned32_decode_ber;
LIB61850_INTERNAL der_type_encoder_f Unsigned32_encode_der;
LIB61850_INTERNAL xer_type_decoder_f Unsigned32_decode_xer;
LIB61850_INTERNAL xer_type_encoder_f Unsigned32_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Unsigned32_H_ */
