/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_UtcTime_H_
#define	_UtcTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UtcTime */
typedef OCTET_STRING_t	 UtcTime_t;

/* Implementation */
LIB61850_INTERNAL extern asn_TYPE_descriptor_t asn_DEF_UtcTime;
LIB61850_INTERNAL asn_struct_free_f UtcTime_free;
LIB61850_INTERNAL asn_struct_print_f UtcTime_print;
LIB61850_INTERNAL asn_constr_check_f UtcTime_constraint;
LIB61850_INTERNAL ber_type_decoder_f UtcTime_decode_ber;
LIB61850_INTERNAL der_type_encoder_f UtcTime_encode_der;
LIB61850_INTERNAL xer_type_decoder_f UtcTime_decode_xer;
LIB61850_INTERNAL xer_type_encoder_f UtcTime_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UtcTime_H_ */
