/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-extended.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "VariableAccessSpecification.h"

static asn_TYPE_member_t asn_MBR_listOfVariable_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ListOfVariableSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfVariable_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfVariable_specs_2 = {
	sizeof(struct VariableAccessSpecification__listOfVariable),
	offsetof(struct VariableAccessSpecification__listOfVariable, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfVariable_2 = {
	"listOfVariable",
	"listOfVariable",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfVariable_tags_2,
	sizeof(asn_DEF_listOfVariable_tags_2)
		/sizeof(asn_DEF_listOfVariable_tags_2[0]) - 1, /* 1 */
	asn_DEF_listOfVariable_tags_2,	/* Same as above */
	sizeof(asn_DEF_listOfVariable_tags_2)
		/sizeof(asn_DEF_listOfVariable_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfVariable_2,
	1,	/* Single element */
	&asn_SPC_listOfVariable_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_VariableAccessSpecification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VariableAccessSpecification, choice.listOfVariable),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_listOfVariable_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfVariable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VariableAccessSpecification, choice.variableListName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"variableListName"
		},
};
static asn_TYPE_tag2member_t asn_MAP_VariableAccessSpecification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* listOfVariable at 760 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* variableListName at 762 */
};
static asn_CHOICE_specifics_t asn_SPC_VariableAccessSpecification_specs_1 = {
	sizeof(struct VariableAccessSpecification),
	offsetof(struct VariableAccessSpecification, _asn_ctx),
	offsetof(struct VariableAccessSpecification, present),
	sizeof(((struct VariableAccessSpecification *)0)->present),
	asn_MAP_VariableAccessSpecification_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_VariableAccessSpecification = {
	"VariableAccessSpecification",
	"VariableAccessSpecification",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_VariableAccessSpecification_1,
	2,	/* Elements count */
	&asn_SPC_VariableAccessSpecification_specs_1	/* Additional specs */
};

